name: Comment on Azure DevOps Work Item When Branch is Created

on:
  create

jobs:
  comment-on-branch-create:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    env:
      AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
      AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

    steps:
      - name: Extract branch name and work item ID
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"
          WORK_ITEM_ID=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+' | head -n 1)
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "work_item_id=$WORK_ITEM_ID" >> $GITHUB_OUTPUT

      - name: Add comment to Azure DevOps work item
        if: steps.extract.outputs.work_item_id != ''
        run: |
          curl -X POST \
            -u :$AZURE_DEVOPS_PAT \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"Branch '${{ steps.extract.outputs.branch }}' was created in GitHub.\"}" \
            "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/wit/workItems/${{ steps.extract.outputs.work_item_id }}/comments?api-version=7.1-preview.3"
