name: On Branch Creation - Comment Work Item & Create Draft PR

on:
  create

jobs:
  handle-branch-create:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name and work item ID
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"
          WORK_ITEM_ID=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+' | head -n 1)
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "work_item_id=$WORK_ITEM_ID" >> $GITHUB_OUTPUT
      
      - name: Capture GitHub actor (branch creator)
        id: actor
        run: |
          echo "actor=${{ github.actor }}" >> $GITHUB_OUTPUT

      - name: Create draft PR
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.extract.outputs.branch }}"
          WORK_ITEM_ID="${{ steps.extract.outputs.work_item_id }}"
          WORK_ITEM_URL="https://dev.azure.com/${{ vars.AZURE_DEVOPS_ORG }}/${{ vars.AZURE_DEVOPS_PROJECT }}/_workitems/edit/$WORK_ITEM_ID"

          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "$BRANCH_NAME" \
            --body "Linked Azure DevOps User Story: $WORK_ITEM_URL" \
            --draft

          PR_URL=$(gh pr view "$BRANCH_NAME" --json url --jq .url)
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          
      - name: Log no commits message
        if: steps.check_commits.outputs.commits_ahead == '0'
        run: echo "No commits between main and ${{ steps.extract.outputs.branch }}. Skipping PR creation."
      
      - name: Add comment to Azure DevOps work item with PR link
        if: steps.extract.outputs.work_item_id != ''
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          ACTOR="${{ steps.actor.outputs.actor }}"
          BRANCH_NAME="${{ steps.extract.outputs.branch }}"
          PR_URL="${{ steps.create_pr.outputs.pr_url }}"
          COMMENT_HTML="<p>Branch '$BRANCH_NAME' was created by <a href="https://github.com/$ACTOR">$ACTOR</a>.</p><br/><p><a href=\"$PR_URL\">View Draft Pull Request</a></p><br/><p><small>Comment created by GitHub Action 🤖</small></p>"

          curl -X POST \
            -u ":$AZURE_DEVOPS_PAT" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg text "$COMMENT_HTML" '{text: $text}')" \
            "https://dev.azure.com/${{ vars.AZURE_DEVOPS_ORG }}/${{ vars.AZURE_DEVOPS_PROJECT }}/_apis/wit/workItems/${{ steps.extract.outputs.work_item_id }}/comments?api-version=7.1-preview.3"
